a = input('Digite algo')
print('O tipo primitivo desse valor é : ',type(a))
print('So tem espaços ?', a.isspace())
print(' É um numero ?', a.isnumeric())
print('É alfabetico ?', a.isalpha())
print('É alfanumerico ? ', a.isalnum())
print('Está em maúsculas ? ',a.isupper())
print('Está em minúsculas ? ',a.islower())
print('Esta capitalizada ? ',a.istitle())